// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/game-hud/Cockpit.tsx": () => import("../components/mockups/game-hud/Cockpit.tsx"),
  "./components/mockups/game-hud/CommandGrid.tsx": () => import("../components/mockups/game-hud/CommandGrid.tsx"),
  "./components/mockups/game-hud/ControlRoom.tsx": () => import("../components/mockups/game-hud/ControlRoom.tsx")
};
